## Chapter 4: Arrays and Vectorized Computation

Here is an example of the efficiency gains from using numpy arrays

In [ ]:
import numpy as np

my_arr = np.arange(1_000_000)

my_list = list(range(1_000_000))

%timeit my_arr2 = my_arr * 2

In [ ]:
%timeit my_list2 = [x * 2 for x in my_list]

### 4.1 The NumPy ndarray: A Multidimensional Array Object

In [ ]:
import numpy as np

data = np.array([[1.5, -0.1, 3.0], [0, -3, 6.5]])

print(data)
data

In [ ]:
print(data)
print(data * 10)
print(data + data)

In [ ]:
print(data.shape)
print(data.dtype)
print(data.ndim)

#### Creating ndarrays

In [ ]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

In [ ]:
print(arr2.ndim)
print(arr2.shape)

In [ ]:
print(arr1.dtype)
print(arr2.dtype)

In [ ]:
print(np.zeros(10))
print(np.zeros((3, 6)))
print(np.empty((2, 3, 2)))

The numpy.arange function is a vectorized version of the built-in range function. It creates an array of evenly spaced values within a given interval.

In [ ]:
np.arange(15)

#### Data Types for ndarrays

In [ ]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
print(arr1.dtype)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr2.dtype)

We can cast numpy arrays to different data types using the astype method. This is useful when we want to ensure that our data is in a specific format for calculations or storage.

In [ ]:
arr = np.array(np.arange(6))
print(arr)
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

If we cast floating to integer, we lose the decimal part. If we cast integer to floating, we get a floating number.

In [ ]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)

arr.astype(np.int32)

We can changes strings to float using astype(float). This is useful when we have a string representation of numbers and we want to perform calculations on them.

In [ ]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype = np.str_)
print(numeric_strings)

numeric_strings.astype(float)

In [ ]:
int_array = np.arange(10)
print(int_array)

calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
print(calibers)

int_array.astype(calibers.dtype)

In [ ]:
zeros_unit32 = np.zeros(10)
print(zeros_unit32)
zeros_unit32 = np.zeros(10, dtype="u4")
zeros_unit32

#### Arithmetic with NumPy Arrays

You can performa arithmetic operations on numpy arrays. The operations are applied element-wise, meaning that each element in the array is operated on independently.
This is different from Python lists, where the operations are not vectorized and require explicit loops to apply the operation to each element.

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr * arr)
print(arr - arr)
print(arr + arr)

Arithmetic operations with scalars propagate the scalar to each element in the array. This is useful for performing operations on all elements of an array without needing to write explicit loops.
The operations are applied element-wise, meaning that each element in the array is operated on independently. This is different from Python lists, where the operations are not vectorized and require explicit loops to apply the operation to each element.

In [ ]:
print(1 / arr)
print(arr ** 2)

Comparison between arrays of the same size yields a boolean array of the same size. This is useful for filtering or masking data based on certain conditions.
The comparison operations are also vectorized, meaning that they are applied element-wise to the arrays. This allows for efficient filtering and masking of data based on conditions.

In [ ]:
print(arr)

arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)

arr2 > arr

#### Basic Indexing and Slicing

In [ ]:
arr = np.arange(10)
print(arr)

print(arr[0])
print(arr[1])
print(arr[5])
print(arr[-1])
print(arr[-2])

print(arr[5:8])

arr[5:8] = 12
print(arr)

An important first distinction from Python's built-in lists is that array slices are views into the same data, so modifying one array will also modify the other. This is different from Python lists, where slices create a new list that is a copy of the original list.
This means that if you modify the slice, the original array will also be modified. This is important to keep in mind when working with numpy arrays, as it can lead to unintended consequences if you're not careful.

In [ ]:
arr_slice = arr[5:8]
print(arr_slice)

arr_slice[1] = 12345
print(arr)

In [ ]:
arr_slice[:] = 64
print(arr)

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)
print(arr2d[2])
print(arr2d[0][2])

In [ ]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d)
print(arr3d[0])

In [ ]:
print(arr3d)

old_values = arr3d[0].copy()
print(old_values)

arr3d[0] = 42
print(arr3d)

arr3d[0] = old_values
print(arr3d)

In [ ]:
print(arr3d[1, 0])
print(arr3d[1, 0, 2])

In [ ]:
print(arr3d)
x = arr3d[1]
print(x)
print(x[0])

#### Indexing with Slices

Indexing with slices is similar to Python lists, but it can be more powerful. You can use slices to extract subarrays or modify parts of an array without creating a copy of the data.
This is useful for working with large datasets, as it allows you to manipulate data without creating unnecessary copies.

In [ ]:
print(arr)
print(arr[1:6])
print(arr[:6])
print(arr[6:])

In [ ]:
print(arr2d)
print(arr2d[:2])

In [ ]:
print(arr2d)
arr2d[:2, 1:]

In [ ]:
lower_dim_slice = arr2d[1, :2]
print(lower_dim_slice)
print(lower_dim_slice.shape)
print(lower_dim_slice.dtype)

In [ ]:
print(arr2d)
arr2d[:2, 2]

In [ ]:
print(arr2d)
print(arr2d[:, :1])
print(arr2d[:, 0])

In [ ]:
print(arr2d)
arr2d[:2, 1:] = 0
print(arr2d)

#### Boolean Indexing

Boolean indexing is a powerful feature of numpy arrays that allows you to select elements based on conditions. You can create a boolean array by applying a condition to an array, and then use that boolean array to index into the original array.
This is useful for filtering data based on certain criteria, such as selecting elements that are greater than a certain value or elements that meet a specific condition.

In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1,2], [-12, -4], [3, 4]])
print(names)
print(data)

In [ ]:
print(names == "Bob")
data[names == "Bob"]

In [ ]:
print(data)
print(data[names == "Bob", 1:])
print(data[names == "Bob", 1])

In [ ]:
print(names != "Bob")
print(~(names == "Bob"))
print(data[~(names == "Bob")])

In [ ]:
cond = names == "Bob"
print(data[~cond])

In [ ]:
print(data)
print(names)
mask = (names == "Bob") | (names == "Will")
print(mask)
print(data[mask])

In [ ]:
print(data)
data[data < 0] = 0
print(data)

In [ ]:
print(names)
data[names != "Joe"] = 7
print(data)

#### Fancy Indexing

In [ ]:
arr = np.zeros((8, 4))

for i in range(8):
    arr[i] = i
print(arr)

In [ ]:
print(arr)
print(arr[[4, 3, 0, 6]])
print(arr[[-3, -5, -7]])

In [ ]:
arr = np.arange(32).reshape((8, 4))
print(arr)
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

In [ ]:
print(arr)
print(arr[[1, 5, 7, 2]])
print(arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

In [ ]:
print(arr)
print(arr[[1, 5, 7, 2], [0, 3, 1, 2]])
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
print(arr)

#### Transposing Arrays and Swapping Axes

Transpose is a method that allows you to swap the rows and columns of an array. This is useful for reshaping data or changing the orientation of an array.
The transpose method is a powerful tool for reshaping data and changing the orientation of an array. It allows you to swap the rows and columns of an array, which can be useful for various applications, such as data analysis or machine learning.  

In [ ]:
arr = np.arange(15).reshape((3, 5))
print(arr)
print(arr.T)

In [ ]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
print(arr)
np.dot(arr.T, arr)

We can also use the @ infix operator to perform matrix multiplication. This is a convenient way to perform matrix operations without needing to use the dot method or the matmul function.
The @ operator is a convenient way to perform matrix multiplication in numpy. It allows you to write more concise and readable code when performing matrix operations. This is especially useful in linear algebra and machine learning applications, where matrix operations are common.

In [ ]:
arr.T @ arr

In [ ]:
print(arr)
print(arr.swapaxes(0, 1))
print(arr)

### 4.2 Pseudorandom Number Generation

In [ ]:
samples = np.random.standard_normal(size=(4, 4))
print(samples)

In [ ]:
from random import normalvariate
N = 1_000_000
%timeit samples = np.array([normalvariate(0, 1) for _ in range(N)])
%timeit np.random.standard_normal(size=N)

In [ ]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))
print(data)
print(type(rng))

### 4.3 Universal Functions: Fast Element-Wise Array Functions

A universal function, or ufunc, is a function that operates element-wise on an array. It is a powerful feature of numpy that allows you to perform operations on arrays without needing to write explicit loops.
Ufuncs are implemented in C, which makes them much faster than Python loops. This is especially important for large datasets, where performance can be a significant concern.

In [ ]:
arr = np.arange(10)
print(arr)
print(type(arr))
print(np.sqrt(arr))
print(np.exp(arr))

In [ ]:
x = rng.standard_normal(8)
print(x)
y = rng.standard_normal(8)
print(y)
print(np.maximum(x, y))

In [ ]:
arr = rng.standard_normal(7) * 5
print(arr)
remainder, whole_part = np.modf(arr)
print(whole_part)
print(remainder)

In [ ]:
print(arr)
out = np.zeros_like(arr)
print(out)
print(np.add(arr, 1))
print(arr)
np.add(arr, 1, out=out)
print(out)

### 4.4 Array-Oriented Programming with Arrays

In [ ]:
points = np.arange(-5, 5, 0.01)
print(len(points))
xs, ys = np.meshgrid(points, points)
print(xs)
print(ys)

In [ ]:
z = np.sqrt(xs ** 2 + ys ** 2)
print(z)

In [ ]:
import matplotlib.pyplot as plt

plt.imshow(z, cmap=plt.cm.gray, extent=[-5, 5, -5, 5])

plt.colorbar()

plt.title("Image plot of $\sqrt{x^2 + y^2}$ for a grid of values")


#### Expressing Conditional Logic as Array Operations

In [ ]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
print(list(zip(xarr, yarr, cond)))
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
print(result)
result = np.where(cond, xarr, yarr)
print(result)  

In [ ]:
arr = rng.standard_normal((4, 4))
print(arr)
print(arr > 0)
print(np.where(arr > 0, 2, arr))
print(np.where(arr > 0, 2, -2))

#### Mathematical and Statistical Methods

In [80]:
rng = np.random.default_rng(seed=12345)
arr = rng.standard_normal((5, 4))
print(arr)
print(arr.shape)
print(arr.mean())
print(np.mean(arr))
print(arr.sum())

[[-1.42382504  1.26372846 -0.87066174 -0.25917323]
 [-0.07534331 -0.74088465 -1.3677927   0.6488928 ]
 [ 0.36105811 -1.95286306  2.34740965  0.96849691]
 [-0.75938718  0.90219827 -0.46695317 -0.06068952]
 [ 0.78884434 -1.25666813  0.57585751  1.39897899]]
(5, 4)
0.0010611661248891013
0.0010611661248891013
0.021223322497782027


In [79]:
print(arr.mean(axis=1))
print(arr.sum(axis=0))

[-0.32248289 -0.38378196  0.4310254  -0.0962079   0.37675318]
[-1.10865307 -1.78448912  0.21785956  2.69650595]


In [ ]:
arr = np.arange(8)
print(arr)
print(arr.cumsum())

In [ ]:
arr = np.arange(9).reshape((3, 3))
print(arr)
print(arr.cumsum(axis=0))
print(arr.cumsum(axis=1))
print(arr.sum(axis=0))

#### Methods for Boolean Arrays

Boolean arrays are arrays of boolean values (True or False). They are useful for filtering data based on conditions or for performing logical operations on arrays.
Boolean arrays can be created using comparison operations, such as greater than or less than. They can also be used to index into other arrays, allowing you to select elements based on conditions.

In [ ]:
rng = np.random.default_rng(seed=12345)
arr = rng.standard_normal(100)

print(arr)
print(arr.sum())
print(arr.mean())
print(arr > 0)
print((arr > 0).sum())
print((arr <= 0).sum())

In [ ]:
bools = np.array([False, False, True, False])
print(bools)
print(bools.any())
print(bools.all())

#### Sorting Arrays

In [ ]:
arr = rng.standard_normal(6)
print(arr)
arr.sort()
print(arr)

In [ ]:
arr = rng.standard_normal((5, 3))
print(arr)
arr.sort(axis=0)
print(arr)
arr.sort(axis=1)
print(arr)

In [ ]:
arr2 = np.array([5, -10, 7, 1, 0, -3])
print(arr2)
sorted_arr2 = np.sort(arr2)
print(sorted_arr2)

#### Unique and Other Set Logic

In [ ]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names)

In [ ]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

Contrast this is the built-in Python set, which is unordered and does not allow duplicates. Numpy's unique function returns the unique elements of an array in sorted order, which can be useful for data analysis or preprocessing.

In [ ]:
sorted(set(names))

### 4.5 File Input and Output with Arrays

In [ ]:
arr = np.arange(10)
print(arr)
np.save("some_array", arr)

In [ ]:
np.load("some_array.npy")

In [ ]:
a = arr
b = arr + 1
c = arr + 2
np.savez("array_archive.npz", a=a, b=b, c=c)

In [ ]:
arch = np.load("array_archive.npz")
print(arch)
print(arch["a"])
print(arch["b"])
print(arch["c"])
print(arch.files)

In [ ]:
np.savez_compressed("array_compressed.npz", a=a, b=b, c=c)
arch = np.load("array_compressed.npz")
arch


### 4.6 Linear Algebra

In [ ]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
print(x)
print(x.shape)
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(y)
print(x.shape)

print(x.dot(y))
print(np.dot(x, y))

In [ ]:
print(x)
print(x.shape)
x @ np.ones(3)

In [ ]:
from numpy.linalg import inv, qr
x = rng.standard_normal((5, 5))
print(x)
print(x.shape)

In [ ]:
mat = x.T @ x
mat_inverse = inv(mat)
print(mat)
print(mat_inverse)
print(mat_inverse @ mat)

### 4.7 Example: Random Walks

In [ ]:
import random
import matplotlib.pyplot as plt
position = 0
print(position)
walk = [position]
print(walk)
nsteps = 1000
for _ in range(nsteps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)

plt.plot(walk[:100])

In [ ]:
nsteps = 10000
rng = np.random.default_rng(seed=12345)
draws = rng.integers(0, 2, size=nsteps)
print(draws)
steps = np.where(draws > 0, 1, -1)
print(steps)
walk = steps.cumsum()
print(walk)

plt.plot(walk)

In [ ]:
print(walk.min())
print(walk.max())

In [ ]:
(np.abs(walk) >= 10).argmax()

#### Simulating Many Random Walks at Once

In [ ]:
nwalks = 5000
nsteps = 1000
draws = rng.integers(0, 2, size=(nwalks, nsteps))
print("draws_shape")
print(draws.shape)
steps = np.where(draws > 0, 1, -1)
print("Steps")
print(steps)
walks = steps.cumsum(axis=1)
print("Walks")
print(walks.shape)
print(walks)


In [72]:
print(walks.min())
print(walks.max())


-124
128


In [73]:
hits30 = (np.abs(walks) >= 30).any(axis=1)
print(hits30)
print(hits30.sum())

[False  True  True ...  True False  True]
3381


In [76]:
crossing_times = (np.abs(walks) >= 30).argmax(axis=1)
print(crossing_times)

[  0 879  59 ... 529   0 655]


In [77]:
crossing_times.mean()

342.213